# Generated by Django 5.2.1 on 2025-05-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_remove_userprofile_secret_hash_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='encrypted_ssh_key',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
