# Generated by Django 5.2.1 on 2025-05-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_project_encrypted_ssh_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='repository_url',
            field=models.URLField(max_length=255, unique=True),
        ),
    ]
