# Generated by Django 5.2.1 on 2025-05-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_project_repository_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='secret_hash',
        ),
        migrations.AddField(
            model_name='project',
            name='encrypted_secret',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
