# Generated by Django 5.2.1 on 2025-05-21 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_project_project_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='name',
        ),
    ]
