# Generated by Django 5.2.1 on 2025-05-21 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_deployment_deploymentstatusmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deployment',
            old_name='commit_uuid',
            new_name='commit_id',
        ),
    ]
