# Generated by Django 5.2.1 on 2025-05-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_rename_commit_uuid_deployment_commit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='commit_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
