# Generated by Django 5.2.1 on 2025-05-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_privatefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatefile',
            name='filepath',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
