# Generated by Django 5.2.1 on 2025-05-21 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_alter_privatefile_filepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='repository_url',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('profile', 'repository_url')},
        ),
    ]
