# Generated by Django 5.2.1 on 2025-05-21 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_alter_project_repository_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='initialized',
            field=models.BooleanField(default=False),
        ),
    ]
