# Generated by Django 5.2.1 on 2025-05-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_privatefile_fileperms'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatefile',
            name='file_type',
            field=models.CharField(choices=[('DEFAULT', 'Default File type'), ('AFTER_BUILD_SCRIPT', 'After Build Script File type')], default='DEFAULT', help_text='Type of the private file', max_length=20),
        ),
    ]
